### ISSUE TITLE
Known issues

### ISSUE THREAD

**Issue by krzysk1** [krzysk1/e415#1]
visual
- glass is too dark - IMPROVED
- reduce interior reflection (too plastic) - IMPROVED

operation
- implement manual operation in controls.tmd - DONE
- set copilot.tmd - DONE

- add other variants: on wheels and floats - DONE

**Comment by Jetjockey10** [comment]
Agree that interior reflections needs work.  Too much reflective movement when viewing from cockpit. (Ray)

**Comment by Jetjockey10** [comment]
Phil, don't look for the rudders, there are none.  Unique design of interlinked flight controls.  Every landing is a crash landing. ha.

**Comment by Jetjockey10** [comment]
I tried land in the snow in CH but was not successful.  I can land in the water at Key West (with the skis)

**Comment by Jetjockey10** [comment]
It is common to read that the Ercoupe does not have rudders, this is not correct.  The Ercoupe does not have rudder PEDALS.  The rudders are there and interconnected with the ailerons and controlled by the steering wheel.

**Comment by Jetjockey10** [comment]
krzysk1, 
I would like to the this Ercoupe brought forward for updating.  There can be several approaches but, I suggest standard (Ercoupe) fixed landing gear be designed and installed.  A separate set of floats would be nice so we can push IPACs for some water to test them.

The Canopy does not open or close.  Most of the switches do not work.  The parking brake does not work.  Comm radio, transponder, wet compass does not work.  Glove compartment doors do not open/close.

The hand crank at the left knee does not work. This may be the canopy control.

The F-KHAR needs to be added to the right fuselage.

A Vintage Owners Manual is included as a pdf file.  Sounds, flight controls, RPM, ASI, VSI and ALT do work.  The wet compass needs adjusting.

**Comment by krzysk1** [comment]
I've added variants for that plane: on wheels and floats. Please download all 3 repositories

**Comment by Jetjockey10** [comment]
Most excellent upgrades.   Great looking floats.  Nice to have the wheeled version also.
Have you noticed the F-KHAR is not present on the right fuselage on any of the versions?
It would be nice if we could kill the engine and stop the prop like the Cub Special.

Thanks for this nice update.

**Comment by Jetjockey10** [comment]
Do you know if the canopy will close and open?  Also, does IPACS support the water rudder animation for the floats?

Ray

**Comment by krzysk1** [comment]
E415 hasn't  canopy which can be opened. It has open air cockpit 😄
Use flaps button to lower the water rudder.

**Comment by Jetjockey10** [comment]
I hope it never rains or hails during flight. Ha,

**Comment by HerveF2** [comment]
strange plane.... with no rudders..... and with no brakes !!!!

- it is really strange to fly only with Joke, and with pedals useless

- it is impossible to use brake (left and right toe)
- easy to land on glacier in Switzerland
